SHOW TABLES;

SELECT *
FROM ACTOR, FILM, CUSTOMER;

SELECT TITLE
FROM FILM;

SELECT NAME
FROM LANGUAGE;

SELECT FIRST_NAME
FROM STAFF;

SELECT DISTINCT RELEASE_YEAR
FROM FILM;

SELECT COUNT(STORE_ID) AS "NUMBER OF STORES"
FROM STORE;

SELECT COUNT(STAFF_ID) AS "NUMBER OF EMPLOYEES"
FROM STAFF;

SELECT COUNT(DISTINCT RENTAL_ID) AS "FILMS RENTED"
FROM RENTAL;

SELECT COUNT(DISTINCT INVENTORY_ID) AS "AVAILABLE FOR RENT"
FROM INVENTORY;

SELECT COUNT(DISTINCT LAST_NAME)
FROM ACTOR;

SELECT DISTINCT length, title AS "Longest Films"
FROM FILM
ORDER BY length DESC
LIMIT 10;

SELECT *
FROM ACTOR
WHERE FIRST_NAME = "SCARLETT";

SELECT * FROM FILM
WHERE title LIKE "%ARMAGEDDON%"
AND length > 100;

SELECT *
FROM FILM;

SELECT COUNT(title) AS "Behind the Scenes"
FROM FILM
WHERE special_features LIKE "%Behind the Scenes%"